version: '2.0'
services:
  ads:
    image: example-adserver/ads
    build:
        context: .
        dockerfile: ./ads/Dockerfile
    ports:
    - "8000:8000"
    environment:
        DB_DSN: "root:root@tcp(mysql:3306)/ads"
        SRV_ADDR: ":8000"
    
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      